language: node_js
node_js:
 - "8"

before_install:
  - npm install -g nexe
  - npm install -g mocha  
  - npm install -g mochawesome
  
 before_scipt:
  - cd Apps//Miner//test//functional-test
  
script:
  - mocha generalTest.js --reporter mochawesome

 
cache:
  directories:
    - "node_modules"