language: node_js
node_js:
 - "8"
 
before_install:
  - npm install  
  - npm install -g nexe
  - npm install -g mocha  
  - npm install -g mochawesome
  
before_script:
  - ls -l
  
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"