language: node_js
node_js:
 - "8"

service_name: travis-pro
repo_token: 6ij5QLeqDysf6O44bAeGfYgUq9WzfO3QA
 
before_install:
  - npm install  
  - npm install -g nexe
  - npm install -g mocha  
  - npm install -g mochawesome
  
before_script:
  - ls -l
  
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage